# Generated by Django 3.1.7 on 2021-03-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ownerRoles',
            fields=[
                ('roleId', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
