# Generated by Django 3.1.7 on 2021-03-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210203_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provinceID', models.IntegerField(primary_key=True, serialize=False)),
                ('provinceName', models.CharField(max_length=30)),
            ],
        ),
    ]
