# Generated by Django 3.1.7 on 2021-03-31 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Owner', '0001_initial'),
        ('accounts', '0006_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityID', models.IntegerField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.ownerroles')),
            ],
        ),
    ]
