# Generated by Django 3.1.7 on 2021-03-31 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0007_admin_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='management_user',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.ownerroles')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('cnic', models.CharField(max_length=16)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('provinceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.province')),
            ],
        ),
        migrations.CreateModel(
            name='custDoc',
            fields=[
                ('custdocID', models.IntegerField(primary_key=True, serialize=False)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('appID', models.IntegerField(primary_key=True, serialize=False)),
                ('appStatus', models.CharField(max_length=16)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
