# Generated by Django 3.1.7 on 2021-03-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_application_custdoc_customer_management_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='provinceID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
