# Generated by Django 3.1.7 on 2021-03-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210331_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
