# Generated by Django 3.1.7 on 2021-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210331_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
