# Generated by Django 3.1.7 on 2021-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Similarity_Index',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
