# Generated by Django 3.1.7 on 2021-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_application_similarity_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='custID',
        ),
        migrations.AlterField(
            model_name='application',
            name='Similarity_Index',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
