# Generated by Django 3.2.3 on 2021-05-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210529_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
