# Generated by Django 3.2.3 on 2021-05-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210530_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpicture',
            name='cnic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
