# Generated by Django 3.2.3 on 2021-05-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_uploadpicture_cnic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
