# Generated by Django 3.2.3 on 2021-05-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210530_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Similarity_Index',
        ),
        migrations.RemoveField(
            model_name='application',
            name='appStatus',
        ),
    ]
