# Generated by Django 3.2.3 on 2021-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210531_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Similarity_Index',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
