# Generated by Django 3.2.3 on 2021-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_application_similarity_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
