# Generated by Django 3.2.3 on 2021-06-05 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 5), null=True),
        ),
    ]
