# Generated by Django 3.2.3 on 2021-06-26 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='numpydataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('data1', models.CharField(max_length=800, null=True)),
                ('data2', models.CharField(max_length=800, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 26), null=True),
        ),
    ]
