# Generated by Django 3.2 on 2021-06-29 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Similarity_Index2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 29), null=True),
        ),
    ]
